name: Deploy to GitHub Pages (disabled auto-run)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

# NOTE: this workflow has been changed to manual dispatch only to avoid
# automatic deployments that conflict with Netlify. To re-enable auto
# deployment on push replace the 'on' section accordingly.


  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Manual workflow placeholder
        run: echo "This workflow is disabled for automatic runs. Use workflow_dispatch to run manually."
        uses: actions/configure-pages@v3
